### ISSUE TITLE
the menu icons cannot be displayed without internet

### ISSUE THREAD

**Issue by breakenknife** [apache/incubator-skywalking#1060]
![22](https://user-images.githubusercontent.com/12994391/38591026-4c05fa8e-3d67-11e8-8c41-09516264e251.png)

As the screenshot shown above.Without internet, it took 24 seconds to load the home page,and both of the small icons of the right menu are missing.

**Comment by wu-sheng** [comment]
@hanahmily Please check whether this can be fixed in beta. I would not think this is a serious problem, but somewhere (ex bank system in this issue ) may don't have internet access.

**Comment by hanahmily** [comment]
The icon resources of AntDesign are located on Aliyun-CDN. According to the description in this [document](https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont), resources can be placed locally.
I'm focusing on some other key features in 5.0.0-beta. So this issue is low priority. If someone want to repair it, I will provide some help.

**Comment by hanahmily** [comment]
fixed in https://github.com/apache/incubator-skywalking-ui/pull/158
