### ISSUE TITLE
Does Trace Data Protocol have any upgrade plan in 5.x series?

### ISSUE THREAD

**Issue by HouZhiHouJue** [apache/incubator-skywalking#1159]
skywalking是一个很好的开源项目，我这边准备直接在公司试用，但是由于5.0对比3.x有协议变更，为了避免升级的麻烦，准备直接上5.0，请问作者有什么好的建议没？另外，还有如题的疑问，辛苦作者 ：）

----
# Translation
SkyWalking is a good open source project, I am going to use it in my company. But the Trace Data Protocol is changed in 5.0 from 3.0. So for avoid the problems, we are going to use 5.0 directly. So I want to ask for suggestions. And does the project team have any upgrade plan?

By @wu-sheng

**Comment by wu-sheng** [comment]
FYI @HouZhiHouJue , I just translate your issue, please keep it in English.

**Comment by wu-sheng** [comment]
Thanks for be interesting in our project. We are going to release the 5.0.0-beta in this month. 

> Does Trace Data Protocol have any upgrade plan in 5.x series?

One of our PMC, @peng-yongsheng , asked for some changes, but didn't be accepted by the project yet. We will be very careful about the upgrade. 

But, I have to say, if you are only using it, you should not care too much about the protocol. Because, the agent, collector and UI always match in our release. For new release, even I assume we change the protocol, the hardest thing you did will be that, upgrade your all agents.

Unless, you are going to process the trace data by your own, or want to work on some other agents or SDKs. If that case, please notice our team, we will ping you before the changes, just like we will ping @liuhaoyang 's .NET agent and @ascrutae 's nodejs agent teams.

**Comment by HouZhiHouJue** [comment]
ok, thanks.
