### ISSUE TITLE
Duplicate traceid in different request

### ISSUE THREAD

**Issue by harley2011** [apache/incubator-skywalking#1254]
Hi, every:
      we are in the process of project integrated skywalking, there is a problem, the different requests of traceid is the same, please help to see what reason, thank you.
Logback configuration is as follows：
![a](https://user-images.githubusercontent.com/4181768/40350023-082e66c2-5ddb-11e8-9e6e-e2bdc30aa883.png)
The same traceid log:
![b](https://user-images.githubusercontent.com/4181768/40350217-bcc5c4cc-5ddb-11e8-8976-aa428cac631f.png)

**Comment by harley2011** [comment]
I need to rewrite the class of "com.github.danielwegener.logback.kafka.KafkaAppender"?

**Comment by wu-sheng** [comment]
> I need to rewrite the class of "com.github.danielwegener.logback.kafka.KafkaAppender"?

I am not familiar with this appender, and it is definitely provided by SkyWalking project.  And I think it is not related to it. The root cause is how do you trace your kafka consume. At normal situation, you need to do some manual instrumentation for Kafka consumer side, e.g. https://github.com/apache/incubator-skywalking/blob/master/docs/en/FAQ/kafka-plugin.md

**Comment by michaelwangwangwang** [comment]
I have the same problem, how to make the traceId of the request inside a 'while(true)'  different

**Comment by binchen-007** [comment]
I also have the same problem. Different requests get the same traceid. May I ask if there is a solution？

**Comment by yujianweilai** [comment]
> I also have the same problem. Different requests get the same traceid. May I ask if there is a solution？

I also have the same problem, do you resolve the problem ?
