### ISSUE TITLE
Deploying on Kubernetes 

### ISSUE THREAD

**Issue by ajanthan** [apache/incubator-skywalking#1282]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Do you have guides/resource to deploy Skywalking on Kubernetes?
___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment]
> Do you have guides/resource to deploy Skywalking on Kubernetes?

@hanahmily Do you have any suggestion? I think you are more familiar than me.

@ajanthan I haven't used Kubernetes to deploy collector in my prod env. We are using Mesos for now. Although, I don't think there should be any problem. The collector only needs to bind and register its IPs/ports to Zookeeper. And the IPs and ports are accessible from agents, meaning IP network is reachable. That is all. 

Then if your agents and collectors need some proxy, which causes the collector IPs are NOT accessible from outside collector cluster(in the cluster, accessible is required), you can use [Direct uplink](https://github.com/apache/incubator-skywalking/blob/master/docs/en/Direct-uplink.md).

**Comment by hanahmily** [comment]
> Do you have guides/resource to deploy Skywalking on Kubernetes?

In short, there are no any guides to deploy Skywalking with K8S. But I could give some advises that may help you.

## Deploy Zookeeper

In order to deploy Zookeeper in an easy way, you should use a popular Docker image. It's good to have a service for Zookeeper pods that can be accessed by agents and collectors.

## Delpy collector cluster

The key step is to config proper pod network for the collector as @wu-sheng described. The simplest way is to use StatefulSets and HeadlessService.

Then the collectors can access each other by using stable network id which is either Pod hostname or Pod DNS.

The deployment of other components isn't too special to give more details.

Hope these guides make sense to you.

**Comment by wu-sheng** [comment]
Closing.
