### ISSUE TITLE
Does the config : agent.sample_n_per_3_secs support such a way like this : 10% 、20% and does the config file : agent.config support dynamic loading?

### ISSUE THREAD

**Issue by Anarchists** [apache/incubator-skywalking#1310]
As title

**Comment by wu-sheng** [comment]
> agent.sample_n_per_3_secs support such a way like this : 10% 、20%

No. But if you want, you could contribute a new optional plugin to support this sample mechanism.  Override `SamplingService` service, by learning from `/apm-sniffer/optional-plugins/trace-ignore-plugin`. This plugin overrides `TraceIgnoreExtendService` service to support new feature.

Welcome to join the community.

> does the config file : agent.config support dynamic loading

This is not an easy YES or NO question. Because some settings, such as application code, buffer size, are hard to change in runtime. So I suggest you focus on which settings do you want to dynamic reload.

**Comment by Anarchists** [comment]
thanks
