### ISSUE TITLE
To skywalking collector cluster, how about usability? version3.2.6.

### ISSUE THREAD

**Issue by hepyu** [apache/incubator-skywalking#1592]
In version 3.2.6.

I mean, if I config collector-cluster, if one of cluster is downtime, is the collector cluster still work? And why.

**Comment by hepyu** [comment]
Oh, I'll describe the point more detail.

For example, there are two nodes used for collector cluster. If one collector node is crash, how to deal in the agent, is it will try to remove or off the crash collector node, auto use the other activity node to transfer data?

I mean, if some node of collector is crash, there won't be loss data, is this true?
And is there some doc to describe the mechanism?

BTW, another question:
When all the collector nodes are crush, then what does the agent will do? Will affect the real program performance?
And is there some doc to describe the mechanism, either?

**Comment by wu-sheng** [comment]
> If one node of collector cluster is crash, what will the agent do? is it will try to remove or off the crash collector node, auto use the other activity node to transfer data?

That is true, of course, you naming nodes set in `agent.config` should have one alive.

> I mean, if some node of collector is crash, skywalking won't loss data, is this true?

No, when the collector crashes, the data in-memory definitely will lose. Agent begins its connect fail-safe mechanism, which will ignore all traces, until connection established again.

> And is there some doc to describe the mechanism?

In 3.x, no. But I think this document in 5.x will help, https://github.com/apache/incubator-skywalking/blob/5.x/docs/en/Architecture.md#multiple-connection-ways . Same mechanism in 3 and 5.

> When all the collector nodes are crush, then what does the agent will do? Will affect the real program performance?

In theory, it should not effect. Because the agent should ignore all traces. But maybe if you memory is not enough, the trace in buffer may cause full GC in some cases. 

Also, if my remember is reliable, if 3 and 5-alpha/beta, if collector is not crash, but suspends by performance or others, this may cause leak.

> And is there some doc to describe the mechanism, either?

No. That is detial thing, you need read codes to understand that part.

**Comment by hepyu** [comment]
got it.
