### ISSUE TITLE
How to use “root cause analysis”？

### ISSUE THREAD

**Issue by wckgo** [apache/incubator-skywalking#1649]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
what is the "root cause analysis"? it means trace and span？
if not，how do i use “root cause analysis”？

**Comment by wu-sheng** [comment]
Depend on what is your scenario. 
1. For a single request, trace and span are for `root cause analysis`.
1. For the whole cluster, topology is a quick view for `root cause analysis`.
1. For a endpoint(service in v5), service dependency maybe, In v6, we have p99/p95/p90/p75/p50 graph for root cause analysis.

So here we are.

**Comment by wu-sheng** [comment]
> Do you use any data mining algorithms for "root cause analysis"?

Right now, we don't have such thing in I known ecosystem. Maybe someone did inside their company.

From my perspective, `data mining` or AI is too heavy for APM, someone definitely is doing this. You should leverage between `what you can get from data mining/AI` and `the payment of people and infra/machines`

**Comment by wckgo** [comment]
Thanks for your answer, Mr. wu.
SkyWalking is awesome.
