### ISSUE TITLE
Code freeze and Integration test for 5.0.0-GA

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-skywalking#1693]
Hi everyone, 

I am going to do release as we planned, 5.0.0-GA will release at the end of Sep. There are several small PRs waiting to confirm. No blocks for this release. @ascrutae has said that, he is going to clear the open PR and issues. 

@ascrutae After you finished, report the test result here, so we can begin our GA release.

**Comment by wu-sheng** [comment]
@ascrutae Look like you finish all in [5.0.0-GA](https://github.com/apache/incubator-skywalking/milestone/27).

@ascrutae @liuhaoyang feel free to do test checks about Java, .Net and Node.js based on current 5.x codebases. I will start release after your confirms.

**Comment by ascrutae** [comment]
Here is the [test report](https://github.com/SkywalkingTest/agent-integration-test-report/blob/c93b25fc52a844b9d11202bfc695545fbcd8a3aa/2018/9/apache/testReport-feature-5.x-2018-09-25-20-39.md) about plugins.

**Comment by ascrutae** [comment]
# Report @ 2018/08/26
the prefix description of Issue:

|prefix|description|
|:---|:---|
|**[AGENT]** | This prefix represent that this issue is an agent issue|
|**[COLLECTOR]**| This prefix represent that this issue is a collector issue|
|**[UI]**| This prefix represent that this issue is an UI issue|
|**[UNKNOWN]**| This prefix represent that everyone should pay attention to this issue|
|**[APP_STANDBY]**| This prefix represent that this issue happened after server started|
|**[APP_SERVICE_PROVIDED]**|This prefix represent that this issue happened after call service|

## Issue
### Application
* **[UI]** There are some error in topology page, and the page is blank.
Here is the screen snapshot:
<img width="1285" alt="wx20180926-045228 2x" src="https://user-images.githubusercontent.com/12436447/46042461-07f36d80-c148-11e8-81da-db48ff3655ba.png">

error log:
```
2.2c6e0b89.async.js:1 Can not apply layout: No such layout `s` found; did you include its JS file?
error @ 2.2c6e0b89.async.js:1
layout @ 2.2c6e0b89.async.js:1
v @ 2.2c6e0b89.async.js:1
(anonymous) @ 2.2c6e0b89.async.js:1
(anonymous) @ 2.2c6e0b89.async.js:1
c @ 2.2c6e0b89.async.js:1
s @ 2.2c6e0b89.async.js:1
value @ 2.2c6e0b89.async.js:1
commitLifeCycles @ index.0b69bae2.js:1
e @ index.0b69bae2.js:1
_ @ index.0b69bae2.js:1
w @ index.0b69bae2.js:1
h @ index.0b69bae2.js:1
d @ index.0b69bae2.js:1

TypeError: Cannot read property 'run' of undefined
    at v (2.2c6e0b89.async.js:1)
    at 2.2c6e0b89.async.js:1
    at 2.2c6e0b89.async.js:1
    at new c (2.2c6e0b89.async.js:1)
    at s (2.2c6e0b89.async.js:1)
    at e.value (2.2c6e0b89.async.js:1)
    at commitLifeCycles (index.0b69bae2.js:1)
    at e (index.0b69bae2.js:1)
    at _ (index.0b69bae2.js:1)
    at w (index.0b69bae2.js:1)
04:42:49.096 index.0b69bae2.js:1 uncaught at e TypeError: Cannot read property 'run' of undefined
    at v (http://localhost:8080/2.2c6e0b89.async.js:1:1206163)
    at http://localhost:8080/2.2c6e0b89.async.js:1:1206324
    at http://localhost:8080/2.2c6e0b89.async.js:1:1206231
    at new c (http://localhost:8080/2.2c6e0b89.async.js:1:1206236)
    at s (http://localhost:8080/2.2c6e0b89.async.js:1:1217962)
    at e.value (http://localhost:8080/2.2c6e0b89.async.js:1:1492167)
    at commitLifeCycles (http://localhost:8080/index.0b69bae2.js:1:411371)
    at e (http://localhost:8080/index.0b69bae2.js:1:414948)
    at _ (http://localhost:8080/index.0b69bae2.js:1:420428)
```

**Comment by wu-sheng** [comment]
@ascrutae Everything goes well at my side, no error log in the browser. Could you recheck again?

**Comment by wu-sheng** [comment]
I also could run Apache release process to provide the dist tar to you for verify, if you need. Ping me in case you need further helps.

**Comment by ascrutae** [comment]
@wu-sheng The bug of UI cause by my environment, and I had rebuild my environment, this issue cannot reproduce.

**Comment by wu-sheng** [comment]
Good to know, please continue to verify the codes. If you feel good to go for release, let me know.

**Comment by ascrutae** [comment]
I had tested and I think the code is ready for release.

**Comment by wu-sheng** [comment]
OK. Thanks, I will begin the release process.
