### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by kofwangshuai** [apache/incubator-skywalking#1882]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by kofwangshuai** [comment]
发现日志中有这样的信息 ： 一个warn 和一个异常

Exception:

INFO 2018-10-29 17:04:37:616 PluginResourcesResolver :  find skywalking plugin define in jar:file:/server/zhan/monitor-agent/agent-agtemos/activations/apm-toolkit-logback-1.x-activation-5.0.0-RC2.jar!/skywalking-plugin.def
INFO 2018-10-29 17:04:37:617 PluginResourcesResolver :  find skywalking plugin define in jar:file:/server/zhan/monitor-agent/agent-agtemos/activations/apm-toolkit-log4j-2.x-activation-5.0.0-RC2.jar!/skywalking-plugin.def
WARN 2018-10-29 17:04:40:476 ProtectiveShieldMatcher :  Byte-buddy occurs exception when match type.
java.lang.IllegalStateException: Cannot resolve type description for org.apache.logging.log4j.spi.ExtendedLoggerWrapper
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:134)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1257)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getSuperClass(TypeDescription.java:7005)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getSuperClass(TypeDescription.java:3329)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:295)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.description.type.TypeDefinition$SuperClassIterator.next(TypeDefinition.java:266)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:35)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.HasSuperTypeMatcher.matches(HasSuperTypeMatcher.java:15)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:101)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matches(ElementMatcher.java:137)
	at org.apache.skywalking.apm.dependencies.net.bytebuddy.matcher.ElementMatcher$Junction$Disjunction.matc


warn ：

INFO 2018-10-29 17:04:42:354 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/plugins/apm-spring-cloud-feign-1.x-plugin-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:354 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/plugins/apm-feign-default-http-9.x-plugin-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:354 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/plugins/apm-mongodb-2.x-plugin-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:354 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/plugins/apm-httpasyncclient-4.x-plugin-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:355 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/activations/apm-toolkit-trace-activation-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:355 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/activations/apm-toolkit-opentracing-activation-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:355 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/activations/apm-toolkit-log4j-1.x-activation-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:355 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/activations/apm-toolkit-logback-1.x-activation-5.0.0-RC2.jar loaded.
INFO 2018-10-29 17:04:42:355 AgentClassLoader :  /server/zhan/monitor-agent/agent-agtemos/activations/apm-toolkit-log4j-2.x-activation-5.0.0-RC2.jar loaded.
WARN 2018-10-29 17:04:47:677 AbstractClassEnhancePluginDefine :  enhance class com.zhan.cloud.agtemos.api.PublicClassApi by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2018-10-29 17:04:47:806 AbstractClassEnhancePluginDefine :  enhance class com.zhan.cloud.agtemos.api.GroupApi by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2018-10-29 17:04:48:122 AbstractClassEnhancePluginDefine :  enhance class com.zhan.cloud.agtemos.api.PublicClassActivitityAwardRecordServiceApi by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2018-10-29 17:04:48:208 AbstractClassEnhancePluginDefine :  enhance class com.zhan.cloud.agtemos.api.ActivitiesSignUpServiceApi by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2018-10-29 17:04:48:402 AbstractClassEnhancePluginDefine :  enhance class com.zhan.cloud.agtemos.api.ActivitiesPromotionServiceApi by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2018-10-29 17:04:49:072 AbstractClassEnhancePluginDefine :  enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2018-10-29 17:04:55:760 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2018-10-29 17:04:58:550 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.

**Comment by wu-sheng** [comment]
English only please. 

> org.apache.logging.log4j.spi.ExtendedLoggerWrapper

This class has been filtered by new release agent. https://github.com/apache/incubator-skywalking/blob/5.x/apm-sniffer/apm-agent/src/main/java/org/apache/skywalking/apm/agent/SkyWalkingAgent.java#L76lL83

**Comment by kikupotter** [comment]
client 6.1:

WARN 2019-06-27 18:48:53:986 AbstractClassEnhancePluginDefine :  enhance class com.lz.report.api.controller.DataManagerController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2019-06-27 18:48:53:987 AbstractClassEnhancePluginDefine :  enhance class com.lz.report.api.controller.DataManagerController by plugin org.apache.skywalking.apm.plugin.spring.webflux.v5.define.RestControllerInstrumentation is not working. Because witness class org.springframework.web.reactive.BindingContext is not existed.
WARN 2019-06-27 18:48:54:017 AbstractClassEnhancePluginDefine :  enhance class com.lz.report.api.controller.ReportInfoController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2019-06-27 18:48:54:017 AbstractClassEnhancePluginDefine :  enhance class com.lz.report.api.controller.ReportInfoController by plugin org.apache.skywalking.apm.plugin.spring.webflux.v5.define.RestControllerInstrumentation is not working. Because witness class org.springframework.web.reactive.BindingContext is not existed.
WARN 2019-06-27 18:48:54:522 AbstractClassEnhancePluginDefine :  enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2019-06-27 18:48:54:523 AbstractClassEnhancePluginDefine :  enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2019-06-27 18:48:54:523 AbstractClassEnhancePluginDefine :  enhance class org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController by plugin org.apache.skywalking.apm.plugin.spring.webflux.v5.define.ControllerInstrumentation is not working. Because witness class org.springframework.web.reactive.BindingContext is not existed.
WARN 2019-06-27 18:48:58:739 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2019-06-27 18:48:58:741 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2019-06-27 18:48:59:950 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2019-06-27 18:48:59:950 AbstractClassEnhancePluginDefine :  enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2019-06-28 10:03:39:976 AbstractClassEnhancePluginDefine :  enhance class com.lz.report.api.controller.DataManagerController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.
WARN 2019-06-28 10:03:39:977 AbstractClassEnhancePluginDefine :  enhance class com.lz.report.api.controller.DataManagerController by plugin org.apache.skywalking.apm.plugin.spring.webflux.v5.define.RestControllerInstrumentation is not working. Because witness class org.springframework.web.reactive.BindingContext is not existed.
WARN 2019-06-28 10:03:40:003 AbstractClassEnhancePluginDefine :  enhance class com.lz.report.api.controller.ReportInfoController by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.RestControllerInstrumentation is not working. Because witness class org.springframework.cache.interceptor.DefaultKeyGenerator is not existed.

**Comment by wu-sheng** [comment]
No witness class is normal. Nothing special.

**Comment by gaoyuanzong** [comment]
skywalking 7.0  agnet:


by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerForLowVersionInstrumentation is not working. Because witness class org.springframework.web.context.support.ServletContextPropertyPlaceholderConfigurer is not existed.


enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v5.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.resource.HttpResource is not existed.
WARN 2020-04-01 14:05:43:477 localhost-startStop-1 AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
WARN 2020-04-01 14:05:43:489 localhost-startStop-1 AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.

**Comment by regardfs** [comment]
> skywalking 7.0 agnet:
> 
> by plugin org.apache.skywalking.apm.plugin.spring.mvc.v4.define.ControllerForLowVersionInstrumentation is not working. Because witness class org.springframework.web.context.support.ServletContextPropertyPlaceholderConfigurer is not existed.
> 
> enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v5.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.resource.HttpResource is not existed.
> WARN 2020-04-01 14:05:43:477 localhost-startStop-1 AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.HandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.HandlerMethodInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.
> WARN 2020-04-01 14:05:43:489 localhost-startStop-1 AbstractClassEnhancePluginDefine : enhance class org.springframework.web.method.support.InvocableHandlerMethod by plugin org.apache.skywalking.apm.plugin.spring.mvc.v3.define.InvocableHandlerInstrumentation is not working. Because witness class org.springframework.web.servlet.view.xslt.AbstractXsltView is not existed.

have u ever solved it yet?
