### ISSUE TITLE
Whether Skywalking can provide code-level visibility？

### ISSUE THREAD

**Issue by JeanJhy** [apache/incubator-skywalking#2439]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
___
### Question
- In the use of the process found that Skywalking call link can only to the request level, there is no specific code details, which compared with the Pinpoint below：
1）Pinpoint can see the concrete class and the method invocation situation
![image](https://user-images.githubusercontent.com/30761558/55464760-62591380-562e-11e9-8ab0-5ce2e9982775.png)
2）Skywaking can only see the invocation of service requests
![image](https://user-images.githubusercontent.com/30761558/55465110-0b077300-562f-11e9-8d9d-76b63606778a.png)

- Which company or project?
personal
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
Do I need to add additional configurations if I want to achieve code-level visibility?

**Comment by wu-sheng** [comment]
First of all, we are not competing with Pinpoint. We have our own landscape and design goals, read [Concepts and Designs](https://github.com/apache/incubator-skywalking/blob/master/docs/en/concepts-and-designs/README.md). We have users in different languages and different scenarios(including tracing, APM and service mesh observability).

So, please, if you want to know something, just ask the question, don't involve pinpoint thing in, which could cause unnecessary discussion.

If you want to trace more methods, read [optional plugins](https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/service-agent/java-agent/README.md#optional-plugins), at least the following three will help you, especially the last one is super powerful to enhance codes without plugin development.
- Trace Spring annotation beans
- Gson serialization lib in optional plugin folder
- Customize enhance Trace methods based on description files, rather than write plugin or change source codes.
