### ISSUE TITLE
[Collector] add prefix for all storage table name

### ISSUE THREAD

**Issue by myoss** [apache/incubator-skywalking#673]
Prefix to increase the table name, easy to distinguish between shared storage cluster

**Comment by wu-sheng** [comment]
Thanks for your suggestion.  Please use English since your comments are documented by ASF. Chinese is not a good way, sadly. :(

Besides the prefix of table name (not a technical problem), I have concerns about sharing the same ES cluster with other system. Because SkyWalking give ES a lot write-load, unless target systems are simple(doubt that), do we recommend people to do such things? @apache/skywalking-committers

**Comment by peng-yongsheng** [comment]
The elasticsearch database provide sharding index. Unless you want to use relation database such as mysql.

**Comment by wu-sheng** [comment]
> The elasticsearch database provide sharding index. Unless you want to use relation database such as mysql.

@myoss Please ignore this, I think @peng-yongsheng misunderstand your point. This is about distinguishing tables only.

**Comment by myoss** [comment]
i want to use in elasticsearch ...

**Comment by peng-yongsheng** [comment]
Sorry, I misunderstand the word distinguish as distributed.

#### I don't recommend every one to share database.
* 1 The collector will write huge data into db, so other systems will be affected.
* 2 The size of the es cluster is different between skywalking and other systems, this will makes it difficult to expand the cluster.

**Comment by wu-sheng** [comment]
As 2 PMC members(@wu-sheng @peng-yongsheng ) don't recommend sharing es. So sorry to say, we are not going to adjust this in official version. If you have these requirements, feel free the download source codes, and changes few codes. It is easy, to be honest.

**Comment by wu-sheng** [comment]
More people require for this feature, I start a new proposal here: #932 @myoss
