### ISSUE TITLE
Recommendation on storing/retrieving plugin specific configuration

### ISSUE THREAD

**Issue by zone1511** [apache/incubator-skywalking#721]
While the Agent downstream is not yet implemented, with in the agent local directory, where is the better place to store plugin specific configuration and how does the plugin read it?

**Comment by wu-sheng** [comment]
First of all, I don't recommend to provide plugin comments, unless it is really necessary or it is only a primary plugin(it it up to you, then). Because, SkyWalking provides auto instrument mechanism. More configurations mean less auto, right.

Still, in tech way, we provide a plugin section in [**plugin config class**](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java#L138). All the config will be set automatically, when you add a new property in [agent config file](https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/config/agent.config) with the same lower case name in Config object.

**Comment by zone1511** [comment]
using single shared config class will make the configuration item couple with the shared config class. Configurable may not be a bad thing if there is a working default. It is use to fine tune the plugin if required.

**Comment by wu-sheng** [comment]
With more plugins, I think I can provide a config item register mechanism, which allow each plugin to register a config class to the **ConfigInitializer**.

Which plugin do you intend to provide if I added this config mechanism?

**Comment by zone1511** [comment]
As related to another thread, I would like to build a conditional sql logging plugin which only log if the sql is execute by certain servlet/mvc action. In this case, I need a config file to store which url(s) should be handle/skip

**Comment by wu-sheng** [comment]
All recent jdbc-related plugins trace sql without any parameter value. If you want to develop private plugin, you can implement your own Config mechanism. 

The project core only provides and maintains the community features (ASF requirements).  So unless we are going to do some open source plugins/features together, this feature will stay in `could be added` rather than `should be added`.
