### ISSUE TITLE
Q: browser instrumentation

### ISSUE THREAD

**Issue by jorgheymans** [apache/incubator-skywalking#851]
### Question
Will skywalking provide something to instrument browser-to-server call, ie inject the agent dynamically on the html/js side and trace http requests starting from the client ?

**Comment by wu-sheng** [comment]
Right now, I didn't provide this type of agent. Because in these days, we are going to release 5.x backend and UI, to provide more features about analysis and visualization. 

Of course, it is on the list, but not recent. But if you or someone want to work with us to contribute js agent in browser, we are glad to help and make this in our **Core features** list.

Roadmap proposal: https://github.com/apache/incubator-skywalking/pull/779

**Comment by jorgheymans** [comment]
OK, thanks for the prompt reply!

Op wo 28 feb. 2018 15:35 schreef 吴晟 Wu Sheng <notifications@github.com>:

**Comment by wu-sheng** [comment]
I will close this, if you don't have any further questions. :)
